<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="49419" started-at="2020-07-02T15:39:27Z" finished-at="2020-07-02T15:40:16Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="49419" started-at="2020-07-02T15:39:27Z" finished-at="2020-07-02T15:40:16Z">
      <class name="TestAuto.TechAutoTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:TestAuto.TechAutoTest@402a079c]" name="beforeMethod" is-config="true" duration-ms="13408" started-at="2020-07-02T21:09:27Z" finished-at="2020-07-02T21:09:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="AdditionTest()[pri:0, instance:TestAuto.TechAutoTest@402a079c]" name="AdditionTest" duration-ms="67" started-at="2020-07-02T21:09:40Z" finished-at="2020-07-02T21:09:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdditionTest -->
        <test-method status="FAIL" signature="SubractionTest()[pri:1, instance:TestAuto.TechAutoTest@402a079c]" name="SubractionTest" duration-ms="47" started-at="2020-07-02T21:09:41Z" finished-at="2020-07-02T21:09:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Not as Expected expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Not as Expected expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at TestAuto.TechAutoTest.SubractionTest(TechAutoTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubractionTest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:TestAuto.TechAutoTest@402a079c]" name="quit" is-config="true" duration-ms="4141" started-at="2020-07-02T21:09:42Z" finished-at="2020-07-02T21:09:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- TestAuto.TechAutoTest -->
      <class name="TestAuto.LoginPageTest">
        <test-method status="PASS" signature="Initializedriver()[pri:0, instance:TestAuto.LoginPageTest@59ec2012]" name="Initializedriver" is-config="true" duration-ms="15871" started-at="2020-07-02T21:09:46Z" finished-at="2020-07-02T21:10:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initializedriver -->
        <test-method status="PASS" signature="initializeObject()[pri:0, instance:TestAuto.LoginPageTest@59ec2012]" name="initializeObject" is-config="true" duration-ms="112" started-at="2020-07-02T21:10:02Z" finished-at="2020-07-02T21:10:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeObject -->
        <test-method status="FAIL" signature="TableDataforTest()[pri:2, instance:TestAuto.LoginPageTest@59ec2012]" name="TableDataforTest" duration-ms="9784" started-at="2020-07-02T21:10:02Z" finished-at="2020-07-02T21:10:11Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at TestAuto.LoginPageTest.TableDataforTest(LoginPageTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TableDataforTest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:TestAuto.LoginPageTest@59ec2012]" name="quit" is-config="true" duration-ms="4079" started-at="2020-07-02T21:10:12Z" finished-at="2020-07-02T21:10:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- TestAuto.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
